### PR TITLE
Add hint string to X509SVID and JWTSVID data structures

### PR DESCRIPTION
**Pull request by dfeldman**
These are already in the SPIFFE spec, and also in the datastore model in SPIRE. I'm planning to implement this feature in SPIRE as a next step. 

Signed-off-by: Daniel Feldman <dfeldman.mn@gmail.com>

### CODE REVIEW

**Comment by azdagron** [comment]
Sorry for the lateness of this review @dfeldman! A few things:

1. It looks like we modified the v1 workload.proto file but then generated (by hand) code for v2? We need to change the v2 workload.proto. You can then run `make generate` to rebuild the code.
2. We should revert all changes to the v1 code (go.sum, go.mod, workload.proto). It is going away.

**Comment by azdagron** [comment]
Hey @dfeldman! Are you still planning on pushing this through? If not, @guilhermocc has volunteered to help out...

**Comment by guilhermocc** [comment]
Hi @dfeldman, I hope you don't mind, but I created another PR for continuing the work done here: https://github.com/spiffe/go-spiffe/pull/212. @azdagron could you review it, please? 😄
After merging it, we can close this PR.

**Comment by azdagron** [comment]
Superseded by #212

**Pull request closed without merging**
