### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by bleggett**
Pulling in `go-spiffe` in caused `go get` to implicitly downgrade some of our other stuff, because of a deploop with the slightly older version of `testify` used here.

So, this is just a minor bump to deps.

### CODE REVIEW

**Comment by bleggett** [comment]
https://github.com/spiffe/go-spiffe/pull/232 is a better way to handle this long-term.

**Comment by azdagron** [comment]
> https://github.com/spiffe/go-spiffe/pull/232 is a better way to handle this long-term.

Yep, agreed. I'll look at that next.

Can you run `go mod tidy` on this? I think there are likely some entries in go.sum that can be removed.

**Comment by azdagron** [comment]
Actually, maybe we should just abandon this PR and merge 232 and let it bring deps up. If we merge yours first, we'll need to resolve merge conflicts.

**Comment by azdagron** [comment]
This PR was subsumed by #232. I'll go ahead and close this out.

**Pull request closed without merging**
